---
# tasks file for buildinventory
- block:
  - name: get domain configuration
    script: readDomainConfig.py {{ NODEMANAGER_DOMAINS }}
    register: domainConfig
    become: yes
    changed_when: False

  - set_fact: domainConfig="{{ domainConfig.stdout_lines }}"

  - name: workaround for non existence of home directory
    set_fact: domainConfig="{{ domainConfig[1:] }}"
    when: domainConfig[0].find("{{ hostvars[inventory_hostname]['ansible_user'] }}") != -1

  - set_fact: domainConfig="{{ domainConfig[0]|from_json }}"

  - name: build Inventory
    add_host: name={{ item.key }} groups=weblogic,{{ item.value.cluster }}
      ansible_user="{{ hostvars[inventory_hostname]['ansible_user'] }}"
    with_dict: "{{ domainConfig }}"

  become: yes
  become_user: "{{ WEBLOGIC_USER }}"
